// auth

POST http://localhost:5555/register
Content-Type: application/json

{
    "id": 1,
    "name": "Guilherme",
    "passwordHash": "123",
    "email": "Blabla blabla",
    "phone": "1234567890"
}

###

POST http://localhost:5555/login
Content-Type: application/json

{
    "name": "Guilherme",
    "password": "123",
}

###
