// auth

POST http://localhost:80/register
Content-Type: application/json

{
    "id": 1,
    "name": "Guilherme",
    "password": "batata",
    "email": "guilherme.werner@tribufu.com",
    "phone": "1234567890"
}

###

POST http://localhost:80/login
Content-Type: application/json

{
    "name": "Guilherme",
    "password": "123"
}

###
