// testimonials

GET http://localhost:5555/testimonials

###

GET http://localhost:5555/testimonials/1

###

POST http://localhost:5555/testimonials
Content-Type: application/json

{
    "id": 5,
    "name": "Trem doido",
    "description": "Blabla blabla",
    "userId": 1,
    "type": "None",
    "location": "Brasil",
    "images": [
        "linda.png"
    ],
    "date": {
        "year": 2012,
        "month": 4,
        "day": 23
    }
}

###

PUT http://localhost:5555/testimonials/2
Content-Type: application/json

{
    "id": 2,
    "name": "Trem doido 2",
    "description": "Blabla blabla",
    "userId": 1,
    "type": "None",
    "location": "Brasil",
    "images": [
        "linda.png"
    ],
    "date": {
        "year": 2012,
        "month": 4,
        "day": 23
    }
}

###

DELETE http://localhost:5555/testimonials/1
