// users

GET http://localhost:80/users

###

GET http://localhost:80/users/1

###

POST http://localhost:80/users
Content-Type: application/json

{
    "id": 1,
    "name": "Guilherme",
    "password": "123",
    "email": "Blabla blabla",
    "phone": "1234567890"
}

###

PUT http://localhost:80/users/1
Content-Type: application/json

{
    "id": 1,
    "name": "Guilherme Werner",
    "password": "123",
    "email": "Blabla blabla",
    "phone": "1234567890"
}

###

DELETE http://localhost:80/users/1
