-- MySQL Script generated by MySQL Workbench
-- Thu Sep 30 15:38:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Animais
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Animais
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Animais` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `Animais` ;

-- -----------------------------------------------------
-- Table `Animais`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Animais`.`User` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `PasswordHash` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NULL,
  `Phone` VARCHAR(25) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Animais`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Animais`.`Article` (
  `Id` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Content` TEXT NOT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Animais`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Animais`.`Comment` (
  `Id` INT UNSIGNED NOT NULL,
  `ArticleId` INT UNSIGNED NOT NULL,
  `UserId` INT UNSIGNED NOT NULL,
  `Content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Comment_User_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_Comment_Article1_idx` (`ArticleId` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User`
    FOREIGN KEY (`UserId`)
    REFERENCES `Animais`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Article1`
    FOREIGN KEY (`ArticleId`)
    REFERENCES `Animais`.`Article` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Animais`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Animais`.`Report` (
  `Id` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `UserId` INT UNSIGNED NOT NULL,
  `Location` VARCHAR(255) NULL,
  `Date` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Report_User1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_Report_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `Animais`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
